const docUsers = [
  { id: 1, regNo: 776, name: "Dr. RAHUL DAHAKE" },
  { id: 2, regNo: 775, name: "Dr. NAMAN AWASTHI" },
  { id: 3, regNo: 774, name: "Dr. AKSHAT LAHOTI" },
  { id: 4, regNo: 773, name: "Dr. PAARAS KOTWAL" },
  { id: 5, regNo: 772, name: "Dr. BHOOMIKA TRIPATHI PANDEY" },
  { id: 6, regNo: 771, name: "Dr. SHREYAS SHAH" },
  { id: 7, regNo: 770, name: "Dr. AMOL DARIBE" },
  { id: 8, regNo: 769, name: "Dr. RITESH SRII" },
  { id: 9, regNo: 768, name: "Dr. ARATI SUNDAR RAJAN" },
  { id: 10, regNo: 767, name: "Dr. JUVERIYA SHAH" },
  { id: 11, regNo: 766, name: "Dr. AHAD RAHMAN" },
  { id: 12, regNo: 765, name: "Dr. RUCHI GULATI" },
  { id: 13, regNo: 763, name: "Dr. KANCHAN" },
  { id: 14, regNo: 762, name: "Dr. TANISHQ RAJORA" },
  { id: 15, regNo: 761, name: "Dr. LOKENDRA SANKLA" },
  { id: 16, regNo: 760, name: "Dr. KAMLESH PAMNANI" },
  { id: 17, regNo: 759, name: "Dr. SATYAJIT ASHOK TEKADE" },
  { id: 18, regNo: 758, name: "Dr. TARUN NAGPAL" },
  { id: 19, regNo: 757, name: "Dr. OMKAR SHETE" },
  { id: 20, regNo: 756, name: "Dr.SANDHYABS" },
  { id: 21, regNo: 755, name: "Dr. SYED ZAKI ANWAR" },
  { id: 22, regNo: 754, name: "Dr. OMER HUSSAIN" },
  { id: 23, regNo: 753, name: "Dr. SURAJ DHILLON" },
  { id: 24, regNo: 752, name: "Dr. HARSH SHAH" },
  { id: 25, regNo: 751, name: "Dr. GAURAV KHEMARIA" },
  { id: 26, regNo: 750, name: "Dr. BASAVARAJ KATAKOL" },
  { id: 27, regNo: 749, name: "Dr. VAIBHAV JAIN" },
  { id: 28, regNo: 748, name: "Dr. ANANDA TIWARI" },
  { id: 29, regNo: 747, name: "Dr. CHANDAN BABU" },
  { id: 30, regNo: 746, name: "Dr. ASHISH KUMAR SHARMA" },
  { id: 31, regNo: 745, name: "Dr. KUNAL MEHTA" },
  { id: 32, regNo: 744, name: "Dr. GOWRISHANKAR RAGHURAMAN" },
  { id: 33, regNo: 743, name: "Dr. SUJIT BOPARDIKAR" },
  { id: 34, regNo: 742, name: "Dr. VINEET GUPTA" },
  { id: 35, regNo: 741, name: "Dr. ABHISHEK SHARMA" },
  { id: 36, regNo: 740, name: "Dr. ANURAG MEHTA" },
  { id: 37, regNo: 739, name: "Dr. ANUBHAV NARESH" },
  { id: 38, regNo: 738, name: "Dr. ROOPAV NAGROTA" },
  { id: 39, regNo: 737, name: "Dr. PARI SAKLECHA" },
  { id: 40, regNo: 736, name: "Dr. BHUWAN SAKLECHA" },
  { id: 41, regNo: 735, name: "Dr. BRIJESH SINGH" },
  { id: 42, regNo: 734, name: "Dr. AIJAZ MALIK" },
  { id: 43, regNo: 733, name: "Dr. CHETAN PATIDAR" },
  { id: 44, regNo: 731, name: "Dr. SONAL MEHTA DAVE" },
  { id: 45, regNo: 730, name: "Dr. RAHUL KHUBCHANDANI" },
  { id: 46, regNo: 729, name: "Dr. DP PATIDAR" },
  { id: 47, regNo: 728, name: "Dr. VIDIT PATHAK" },
  { id: 48, regNo: 727, name: "Dr. MIHIR JOSHI" },
  { id: 49, regNo: 726, name: "Dr. NAMAN PANDYA" },
  { id: 50, regNo: 732, name: "Dr. VIPIN SHARMA" },
  { id: 51, regNo: 725, name: "Dr. GAUTAM LAL" },
  { id: 52, regNo: 724, name: "Dr. VIHANG NAPHADE" },
  { id: 53, regNo: 723, name: "Prof. PRAVAL PRATAP SINGH" },
  { id: 54, regNo: 722, name: "Dr. SRISHTI PUNJANI" },
  { id: 55, regNo: 721, name: "Dr. NEETU M SHAH" },
  { id: 56, regNo: 720, name: "Dr. MANAN" },
  { id: 57, regNo: 719, name: "Dr. BARKHA MAHESHWARI" },
  { id: 58, regNo: 718, name: "Dr. VIMESH PATEL" },
  { id: 59, regNo: 717, name: "Dr. JOGINDER SINGH" },
  { id: 60, regNo: 716, name: "Dr. CHITTRANJAN KUMAR SINGH" },
  { id: 61, regNo: 715, name: "Dr. SURENDRA GUJARKAR" },
  { id: 62, regNo: 714, name: "Dr. CHETAN DARNE" },
  { id: 63, regNo: 713, name: "Dr. NIKITA BHATNAGAR" },
  { id: 64, regNo: 712, name: "Prof. MOHAN KUMAR KP" },
  { id: 65, regNo: 711, name: "Dr. RAHUL KULKARNI" },
  { id: 66, regNo: 710, name: "Dr. PRADEEP SHARMA" },
  { id: 67, regNo: 709, name: "Dr. PAREEDHI ARORA" },
  { id: 68, regNo: 708, name: "Dr. ORNELYA FERNANDES" },
  { id: 69, regNo: 707, name: "Dr. VIDYA PANDIT" },
  { id: 70, regNo: 705, name: "Dr. JAIDEEP SINGH CHAUHAN" },
  { id: 71, regNo: 704, name: "Dr. MAYUR KUMAR SONI" },
  { id: 72, regNo: 703, name: "Dr. HIMALAYA UDANIYA" },
  { id: 73, regNo: 702, name: "Dr. RAJUL KHARE" },
  { id: 74, regNo: 701, name: "Prof. SURYAHANTHMIHIRAN SIVASUBRAMANI" },
  { id: 75, regNo: 700, name: "Prof. DR KAPIL PATIL" },
  { id: 76, regNo: 699, name: "Dr. SHRUTI CHAURASIA" },
  { id: 77, regNo: 706, name: "Dr. NENCY PARIHAR" },
  { id: 78, regNo: 698, name: "Dr. AAKASH HARSHAD TAKVANI" },
  { id: 79, regNo: 697, name: "Prof. RIMMY " },
  { id: 80, regNo: 696, name: "Dr. PRAVIN PRADEEP JOSHI" },
  { id: 81, regNo: 695, name: "Dr. VISHAL MUJUMDAR" },
  { id: 82, regNo: 694, name: "Dr. DR SHASWAT JAIN" },
  { id: 83, regNo: 693, name: "Dr. SHITIJA NEVE" },
  { id: 84, regNo: 692, name: "Dr. SURUTHI S" },
  { id: 85, regNo: 691, name: "Dr. NITIN SHYAM SUNDAR AGARWAL" },
  { id: 86, regNo: 690, name: "Dr. PRASANTH S" },
  { id: 87, regNo: 689, name: "Dr. BHARAT RATHI" },
  { id: 88, regNo: 688, name: "Dr. MANSI LAGU" },
  { id: 89, regNo: 687, name: "Dr. ASEEM NEMA" },
  { id: 90, regNo: 686, name: "Dr. ARPIT SAMIR SHAH" },
  { id: 91, regNo: 685, name: "Dr. SHRADDHA TIWARI" },
  { id: 92, regNo: 684, name: "Dr. PRIYA JOSHI" },
  { id: 93, regNo: 683, name: "Dr. YOGRAJ MEHRA" },
  { id: 94, regNo: 682, name: "Dr. SHILPA HANSRAJANI" },
  { id: 95, regNo: 681, name: "Dr. SHITIJ BHARGAVA" },
  { id: 96, regNo: 680, name: "Dr. DR SANTOSH MISHRA" },
  { id: 97, regNo: 679, name: "Dr. NEHA DESHPANDE" },
  { id: 98, regNo: 764, name: "Dr. RAJESH GAIKWAD" },
  { id: 99, regNo: 678, name: "Dr. YOGESH LOKSH" },
  { id: 100, regNo: 677, name: "Dr. MADHURI MESHRAM" },
  { id: 101, regNo: 676, name: "Dr. KAPIL SANGHVI" },
  { id: 102, regNo: 675, name: "Dr. BHAVANA S BAGALAD" },
  { id: 103, regNo: 674, name: "Prof. CHETHAN B R" },
  { id: 104, regNo: 673, name: "Dr. CHIRAG THAKAR" },
  { id: 105, regNo: 672, name: "Dr. MOHAMMAD ASIM" },
  { id: 106, regNo: 671, name: "Dr. ZAHEER AHMED ANSARI " },
  { id: 107, regNo: 670, name: "Dr. SAMEER SHAIKH" },
  { id: 108, regNo: 669, name: "Dr. SARTHAK SHRIVASTAV" },
  { id: 109, regNo: 668, name: "Dr. ABHINAV SUBHASHCHANDRA BAHETI" },
  { id: 110, regNo: 667, name: "Dr. VINNY BHASIN" },
  { id: 111, regNo: 666, name: "Dr. PRATIK SANJAY MANDALE" },
  { id: 112, regNo: 665, name: "Dr. NEHA MEHROTRA" },
  { id: 113, regNo: 664, name: "Dr. NIKHIL DEORE" },
  { id: 114, regNo: 663, name: "Dr. HARSH KUMAR" },
  { id: 115, regNo: 662, name: "Dr. HITESH S MOTWANI" },
  { id: 116, regNo: 661, name: "Dr. NITIN NAWALE" },
  { id: 117, regNo: 660, name: "Dr. KATHAR SAGAR RAMESH" },
  { id: 118, regNo: 659, name: "Dr. VARUN WADHWANI" },
  { id: 119, regNo: 658, name: "Dr. PRATAP DHAWALE" },
  { id: 120, regNo: 657, name: "Dr. YASHODEEP CHAUHAN" },
  { id: 121, regNo: 656, name: "Dr Sachin Thakur" },
  { id: 122, regNo: 655, name: "Dr. ASHUTOSH DUTT PATHAK" },
  { id: 123, regNo: 654, name: "Dr. RISHI THUKRAL" },
  { id: 124, regNo: 653, name: "Dr. DR AROON K. BENGANI" },
  { id: 125, regNo: 652, name: "Dr. ASHWIN MYSORE" },
  { id: 126, regNo: 650, name: "Dr. VAIBHAV JAISWAL" },
  { id: 127, regNo: 649, name: "Dr. AMIT BHARDWAJ" },
  { id: 128, regNo: 648, name: "Dr. ARPIT BINDA" },
  { id: 129, regNo: 651, name: "Dr. DR ROHIT KUMAR SINGH WASIN" },
  { id: 130, regNo: 647, name: "Dr. RISHABH TRIVEDI" },
  { id: 131, regNo: 646, name: "Dr. ABDULQADIR ATTARI" },
  { id: 132, regNo: 645, name: "Dr. SWARNJEET SINGH GAMBHIR" },
  { id: 133, regNo: 644, name: "Dr. DHAWAL GOYAL" },
  { id: 134, regNo: 643, name: "Dr. SANKALP MITTAL" },
  { id: 135, regNo: 642, name: "Dr. SATISH BHARDWAJ" },
  { id: 136, regNo: 642, name: "Dr. ALOK BHARDWAJ" },
  { id: 137, regNo: 641, name: "Dr. MANISH KANUNGO" },
  { id: 138, regNo: 640, name: "Dr. GHANSHYAM GAUR" },
  { id: 139, regNo: 638, name: "Dr. VARUN SURYAWANSHI" },
  { id: 140, regNo: 639, name: "Dr. AKANKSHA MAHESHWARI" },
  { id: 141, regNo: 637, name: "Dr. ABHIJEET BHASIN" },
  { id: 142, regNo: 636, name: "Dr. MAHESH NEURGAONKAR" },
  { id: 143, regNo: 635, name: "Dr. AMIT SINGH CHOUDHARY" },
  { id: 144, regNo: 634, name: "Dr. NAMITA KAMBLE" },
  { id: 145, regNo: 633, name: "Dr. SANKET SHRIVASTAVA" },
  { id: 146, regNo: 632, name: "Dr. DEEPMALA MAURYA" },
  { id: 147, regNo: 631, name: "Dr. ABBAS UNWALA" },
  { id: 148, regNo: 630, name: "Dr. GUNJAN CHAUDHARY" },
  { id: 149, regNo: 629, name: "Dr. DR SANKET SHINDE" },
  { id: 150, regNo: 628, name: "Dr. SACHIN S. DUGAD" },
  { id: 151, regNo: 627, name: "Dr. YOGESH SAKHARAM GHUGARE" },
  { id: 152, regNo: 626, name: "Dr. MD ASIF KO" },
  { id: 153, regNo: 625, name: "Dr. GULSHAN JAIN" },
  { id: 154, regNo: 624, name: "Dr. NILIMA AGRAWAL" },
  { id: 155, regNo: 623, name: "Dr. NIKITA SONI" },
  { id: 156, regNo: 622, name: "Dr. DIVASHREE SHARMA " },
  { id: 157, regNo: 621, name: "Dr. TARUN VERMA" },
  { id: 158, regNo: 620, name: "Dr. PALAK JOSHI" },
  { id: 159, regNo: 618, name: "Dr. KAVITA RAJ" },
  { id: 160, regNo: 617, name: "Dr. NEELAM NAGLE" },
  { id: 161, regNo: 619, name: "Dr. NAMAN KHARE" },
  { id: 162, regNo: 616, name: "Dr. ABHISHEK SONI" },
  { id: 163, regNo: 614, name: "Dr. JANVI THISKE KHARE" },
  { id: 164, regNo: 613, name: "Dr. ARVIND ARORA" },
  { id: 165, regNo: 612, name: "Dr. SONAKSHI RANKA" },
  { id: 166, regNo: 10, name: "Dr. RISHABH SHUKLA" },
  { id: 167, regNo: 611, name: "Dr. SIDDHARTH JAIN" },
  { id: 168, regNo: 610, name: "Dr. KRITIKA CHITLANGIA" },
  { id: 169, regNo: 609, name: "Dr. BHUMIKA NAVLANI" },
  { id: 170, regNo: 608, name: "Dr. YOGESH SHARMA" },
  { id: 171, regNo: 615, name: "Dr. NAMITA MISHRA" },
  { id: 172, regNo: 606, name: "Dr. RITUPARNA VYAS" },
  { id: 173, regNo: 607, name: "Dr. SHUCHI JAIN" },
  { id: 174, regNo: 605, name: "Dr. JITENDRA REVAMKAR" },
  { id: 175, regNo: 604, name: "Dr. NEERAJ SHARMA" },
  { id: 176, regNo: 603, name: "Prof. JYOTSNA SHUKLA" },
  { id: 177, regNo: 602, name: "Dr. YOGESH PAL SINGH" },
  { id: 178, regNo: 601, name: "Dr. HARSHVARDHAN VYAS" },
  { id: 179, regNo: 600, name: "Prof. LAKSHYA KUMAR" },
  { id: 180, regNo: 599, name: "Dr. MAYANK SINGH" },
  { id: 181, regNo: 598, name: "Dr. SUMUKH MUNIRAJ" },
  { id: 182, regNo: 597, name: "Dr. AJIT G. SHETTY " },
  { id: 183, regNo: 596, name: "Dr. SHIKHA DHAKAD" },
  { id: 184, regNo: 595, name: "Dr. C.MURUGAVEL" },
  { id: 185, regNo: 594, name: "Dr. DHIRENDRA PRATAP SINGH" },
  { id: 186, regNo: 593, name: "Dr. CHETAN RAYAL" },
  { id: 187, regNo: 592, name: "Dr. SHILPA DHAKAD" },
  { id: 188, regNo: 591, name: "Dr. DATTATRAYA A BHAJIBHAKARE" },
  { id: 189, regNo: 590, name: "Dr. HEMALATHA DARA" },
  { id: 190, regNo: 589, name: "Dr. MS.SANGHMITRA DASGUPTA" },
  { id: 191, regNo: 588, name: "Dr. KSHITIJ BANG" },
  { id: 192, regNo: 587, name: "Dr. VIRENDRA PARMAR" },
  { id: 193, regNo: 536, name: "Dr. KARTIK KAPOOR" },
  { id: 194, regNo: 582, name: "Dr. PARASHAR DESAI" },
  { id: 195, regNo: 581, name: "Dr. NIKHIL SHARMA" },
  { id: 196, regNo: 580, name: "Dr. ANJALI KAPOOR" },
  { id: 197, regNo: 583, name: "Dr. MAITRY M SHAH" },
  { id: 198, regNo: 579, name: "Dr. MEGHA JAIN" },
  { id: 199, regNo: 578, name: "Dr. NIMISH NIMEYA" },
  { id: 200, regNo: 577, name: "Dr. PANKAJ JAIN" },
  { id: 201, regNo: 576, name: "Dr. BASANT CHANDNA" },
  { id: 202, regNo: 575, name: "Dr. SAURABH VERMA" },
  { id: 203, regNo: 574, name: "Dr. AMRITPAL SINGH GREWAL" },
  { id: 204, regNo: 573, name: "Dr. VIKAS DEV" },
  { id: 205, regNo: 572, name: "Dr. RAHUL SHRIVASTAVA" },
  { id: 206, regNo: 571, name: "Dr. ANUJ CHANDAK" },
  { id: 207, regNo: 570, name: "Dr. SONAL TRIPATHI" },
  { id: 208, regNo: 569, name: "Dr. HEMAL HASMUKHBHAI SHAH" },
  { id: 209, regNo: 568, name: "Dr. ARCHIT TIWARI" },
  { id: 210, regNo: 567, name: "Dr. DEV KUMAR GARG" },
  { id: 211, regNo: 566, name: "Dr. PRATEEK AGARWAL" },
  { id: 212, regNo: 565, name: "Dr. VIJETA MAKHIJA" },
  { id: 213, regNo: 564, name: "Dr. NISHTHA MAKHIJA" },
  { id: 214, regNo: 563, name: "Dr. ABRAHAM ISAAC" },
  { id: 215, regNo: 562, name: "Dr. SHIKHAR PRATAP CHAUHAN" },
  { id: 216, regNo: 561, name: "Dr. PRAKASH JAIN" },
  { id: 217, regNo: 560, name: "Dr. PRATIBHA SINGH THAKUR" },
  { id: 218, regNo: 559, name: "Dr. MANOHAR VARMA" },
  { id: 219, regNo: 558, name: "Dr. M.SHAFIYAH" },
  { id: 220, regNo: 557, name: "Dr. DHANUSH CV" },
  { id: 221, regNo: 556, name: "Dr. PEYUSH PRATAP SINGH SIKARWAR" },
  { id: 222, regNo: 555, name: "Dr. SURBHI WADHWANI" },
  { id: 223, regNo: 554, name: "Dr. RAJESHWAR SINGH" },
  { id: 224, regNo: 553, name: "Dr. RASHI JAIN" },
  { id: 225, regNo: 552, name: "Dr. JAYASHREE CHAUDHARI" },
  { id: 226, regNo: 551, name: "Dr. AKSHAT KUMAR SHARMA" },
  { id: 227, regNo: 550, name: "Dr. ABDUL MIRAN .A" },
  { id: 228, regNo: 549, name: "Dr. SHRUTI PATIL" },
  { id: 229, regNo: 548, name: "Dr. MEHTA PAYAL" },
  { id: 230, regNo: 547, name: "Dr. AYUSH MISHRA" },
  { id: 231, regNo: 546, name: "Dr. PREETHAM M P" },
  { id: 232, regNo: 545, name: "Dr. LUKE KALE" },
  { id: 233, regNo: 544, name: "Dr. SONIYA HATILA" },
  { id: 234, regNo: 543, name: "Dr. ASHISH KAPOOR" },
  { id: 235, regNo: 542, name: "Dr. GURUPRASAD UIKEY" },
  { id: 236, regNo: 541, name: "Dr. SNEHAL DHAMANDE" },
  { id: 237, regNo: 540, name: "Dr. AMIT GILANI" },
  { id: 238, regNo: 539, name: "Dr. YOGENDRA SABOO" },
  { id: 239, regNo: 538, name: "Dr. ARPIT JAIN" },
  { id: 240, regNo: 535, name: "Dr. MANPREET HORA" },
  { id: 241, regNo: 534, name: "Dr. ANURAG BHARGAVA" },
  { id: 242, regNo: 533, name: "Dr. ARCHITA GANGWAL PATODI" },
  { id: 243, regNo: 532, name: "Dr. VISHALATCHI L" },
  { id: 244, regNo: 531, name: "Dr. HIMANSHU SHARMA" },
  { id: 245, regNo: 530, name: "Dr. MANJUNATH BAVIKATTI" },
  { id: 246, regNo: 529, name: "Dr. KIRAN SHANKAR ARADHYA" },
  { id: 247, regNo: 528, name: "Dr. MAHENDRA SOMASHEKHARAIAH BAGUR" },
  { id: 248, regNo: 527, name: "Dr. SUNIL KUMAR RAMACHANDRAN" },
  { id: 249, regNo: 526, name: "Dr. V. S. MOHAN" },
  { id: 250, regNo: 525, name: "Dr. SHANTA KORGAONKAR" },
  { id: 251, regNo: 524, name: "Dr. SANJAY TULSIDAS ASNANI" },
  { id: 252, regNo: 523, name: "Dr. HEMANSHU DHIRAJLAL MEHTA" },
  { id: 253, regNo: 522, name: "Dr. JATIN KOTHARI" },
  { id: 254, regNo: 521, name: "Dr. LUBNA FIRDOSE A" },
  { id: 255, regNo: 520, name: "Dr. AMIT V. GUPTA" },
  { id: 256, regNo: 519, name: "Dr. PARAS K RAWAT" },
  { id: 257, regNo: 518, name: "Dr. ANJALI CHHABARIYA" },
  { id: 258, regNo: 517, name: "Dr. SHAMI SONI" },
  { id: 259, regNo: 516, name: "Dr. PRACHI GURAV " },
  { id: 260, regNo: 515, name: "Dr. PRASHANTHI REDDY" },
  { id: 261, regNo: 514, name: "Dr. NIMAI MISHRA" },
  { id: 262, regNo: 513, name: "Dr. TIMBADIYA VIJAY" },
  { id: 263, regNo: 512, name: "Dr. ABHISHEK JAIN" },
  { id: 264, regNo: 511, name: "Dr. HARSHAD PANDEY" },
  { id: 265, regNo: 510, name: "Dr. HARSH SAINI" },
  { id: 266, regNo: 509, name: "Dr. MEENU MAHAJAN" },
  { id: 267, regNo: 508, name: "Dr. SURENDRA BABU" },
  { id: 268, regNo: 507, name: "Dr. SWAPNIL TILEKAR" },
  { id: 269, regNo: 506, name: "Dr. VINAYAK DAMODHAR KANAKDANDE" },
  { id: 270, regNo: 505, name: "Dr. NILESH V FATALE" },
  { id: 271, regNo: 504, name: "Dr. MAYURDHWAJ GOHIL" },
  { id: 272, regNo: 503, name: "Dr. NEHA KALA DEVRA" },
  { id: 273, regNo: 502, name: "Dr. VIRENDRA SINGH DEVARA" },
  { id: 274, regNo: 501, name: "Dr. APOORV PATODI" },
  { id: 275, regNo: 500, name: "Dr. VIREN PATEL" },
  { id: 276, regNo: 492, name: "Dr. AKHILESH JAIN" },
  { id: 277, regNo: 584, name: "Dr. CHETAN AHIRE" },
  { id: 278, regNo: 585, name: "Dr. PRASHANT BHURAT" },
  { id: 279, regNo: 586, name: "Dr. ANSHUL JAIN" },
  { id: 280, regNo: 537, name: "Dr. SMITA CHAUHAN" },
  { id: 281, regNo: 499, name: "Dr. SANDEEP KUMAR DUBEY" },
  { id: 282, regNo: 498, name: "Dr. NIKHIL PUROHIT" },
  { id: 283, regNo: 497, name: "Dr. RUCHI ARORA" },
  { id: 284, regNo: 496, name: "Dr. VIJAY DHANARE" },
  { id: 285, regNo: 495, name: "Dr. AJMAL FASALUDHEEN" },
  { id: 286, regNo: 494, name: "Dr. PRABATH SINGH VP" },
  { id: 287, regNo: 493, name: "Dr. PRINCE JAIN" },
  { id: 288, regNo: 491, name: "Dr. AKASH CHANDRAKANT PRAJAPATI" },
  { id: 289, regNo: 490, name: "Dr. ATUL KUMAR YADAV" },
  { id: 290, regNo: 489, name: "Dr. PRATESH NITIN DHOLABHAI" },
  { id: 291, regNo: 488, name: "Dr. AJESH V FADADU" },
  { id: 292, regNo: 487, name: "Dr. PRATIK FALDU" },
  { id: 293, regNo: 486, name: "Dr. TARUN SHARMA" },
  { id: 294, regNo: 485, name: "Dr. GAURAVI JAIN" },
  { id: 295, regNo: 484, name: "Dr. MAYUR BHOJANI" },
  { id: 296, regNo: 481, name: "Dr. VANITHA SHANMUGHAM" },
  { id: 297, regNo: 483, name: "Dr. HEMA D" },
  { id: 298, regNo: 482, name: "Dr. PRABHU SUNDARA RAMAN" },
  { id: 299, regNo: 480, name: "Dr. N SENTHIL KUMAR" },
  { id: 300, regNo: 479, name: "Dr. S VIJAY PARTHIBAN" },
  { id: 301, regNo: 478, name: "Dr. PARTH PUROHIT" },
  { id: 302, regNo: 477, name: "Dr. VIKAS DATTATRAY PATIL" },
  { id: 303, regNo: 476, name: "Dr. RANJAN KUMAR" },
  { id: 304, regNo: 475, name: "Dr. SOMA MALLICK" },
  { id: 305, regNo: 471, name: "Dr.RAVIKUMAR DHARMENDRABHAI PATEL" },
  { id: 306, regNo: 474, name: "Dr. DHERAJ. S" },
  { id: 307, regNo: 473, name: "Prof. ANIL K SHEORAIN" },
  { id: 308, regNo: 472, name: "Dr. KRITHIKA NARAYANAN" },
  { id: 309, regNo: 470, name: "Dr. NIVEDHA MENON" },
  { id: 310, regNo: 469, name: "Dr. PIYUSH AGRAWAL" },
  { id: 311, regNo: 468, name: "Dr. PRADEEP JAIN" },
  { id: 312, regNo: 467, name: "Dr. MITHUN KASHYAP J" },
  { id: 313, regNo: 466, name: "Dr. DEEPA PRADEEP VAGHASIYA" },
  { id: 314, regNo: 465, name: "Dr. MONALI SHAH" },
  { id: 315, regNo: 464, name: "Dr. DISHAN SHAH" },
  { id: 316, regNo: 463, name: "Dr. OMKAR RAJENDRA YADAV" },
  { id: 317, regNo: 462, name: "Dr. SUBODH KANDGE" },
  { id: 318, regNo: 461, name: "Dr. RUDRASWAMI HIREMATH" },
  { id: 319, regNo: 460, name: "Dr. PARIKSHIT SUBHASHRAO SONDANKAR" },
  { id: 320, regNo: 459, name: "Dr. PRANAV P SHAH" },
  { id: 321, regNo: 458, name: "Dr. ARPIT PATEL" },
  { id: 322, regNo: 457, name: "Dr. NILESH PATEL" },
  { id: 323, regNo: 456, name: "Dr. SUMANTA ROY CHOWDHURY" },
  { id: 324, regNo: 455, name: "Dr. PANCHAM AGGARWAL" },
  { id: 325, regNo: 454, name: "Dr. GAURAV PATEL" },
  { id: 326, regNo: 453, name: "Dr. KALYANI DESHMUKH" },
  { id: 327, regNo: 452, name: "Dr. AKHIL RATHI" },
  { id: 328, regNo: 451, name: "Dr. ESHA VERMA" },
  { id: 329, regNo: 450, name: "Dr. KAPIL VIJAY CHAUTRAY" },
  { id: 330, regNo: 449, name: "Dr. ARPIT RAMANI" },
  { id: 331, regNo: 419, name: "Dr. ASHI MITTAL" },
  { id: 332, regNo: 448, name: "Dr. PRAVINKUMAR NATVARLAL PATEL" },
  { id: 333, regNo: 447, name: "Dr. SHAILESH MENAT" },
  { id: 334, regNo: 446, name: "Dr. JATAN KANUBHAI PATEL" },
  { id: 335, regNo: 445, name: "Dr.VIKAS BHOJANI" },
  { id: 336, regNo: 444, name: "Dr. ATUL KULKARNI" },
  { id: 337, regNo: 443, name: "Dr. JIGARKUMAR CHANDRAKANTBHAI PATEL" },
  { id: 338, regNo: 441, name: "Dr. NILAM RANCHODBHAI PATEL" },
  { id: 339, regNo: 8, name: "Dr. NOUMAN KHAN" },
  { id: 340, regNo: 440, name: "Dr. MANISH LIMBACHIYA" },
  { id: 341, regNo: 439, name: "Dr. BRIJESH PATEL" },
  { id: 342, regNo: 438, name: "Dr. DARSHAK CHAUDHARI" },
  { id: 343, regNo: 437, name: "Dr. Rajkumar Mantri" },
  { id: 344, regNo: 436, name: "Dr. K K PATEL" },
  { id: 345, regNo: 435, name: "Dr. BHARAT BHUSHAN AGRAWAL" },
  { id: 346, regNo: 434, name: "Dr. DHEERAJ GUPTA" },
  { id: 347, regNo: 433, name: "Dr. KUNAL KOTHARI" },
  { id: 348, regNo: 432, name: "Dr. ASHISH JAIN" },
  { id: 349, regNo: 431, name: "Dr. ANITA BHAVIK DOSHI" },
  { id: 350, regNo: 430, name: "Dr. NAMITA AGRAWAL" },
  { id: 351, regNo: 429, name: "Dr. GAUTAMKUMAR VADHER" },
  { id: 352, regNo: 428, name: "Dr. TANVY SUYASH SADEKAR" },
  { id: 353, regNo: 427, name: "Dr. SARNAM SINGH GARG" },
  { id: 354, regNo: 426, name: "Dr. PREKSHA GAIKWAD" },
  { id: 355, regNo: 425, name: "Dr. ASHISH SINGH" },
  { id: 356, regNo: 424, name: "Dr. ASHISH RAO" },
  { id: 357, regNo: 423, name: "Dr. LAXMIKANT BOHRE" },
  { id: 358, regNo: 410, name: "Dr. PARUL JAIN" },
  { id: 359, regNo: 409, name: "Dr. NEELAM VIJAYWARGIYA" },
  { id: 360, regNo: 408, name: "Dr. MAMTA SINGH" },
  { id: 361, regNo: 407, name: "Dr. DEEPASHRI H KAMBALIMATH" },
  { id: 362, regNo: 406, name: "Dr. VEENA KALBURGI" },
  { id: 363, regNo: 405, name: "Dr. UNNATI PITALE" },
  { id: 364, regNo: 422, name: "Dr. MUKESHKUMAR GIRIDHARBHAI PATEL" },
  { id: 365, regNo: 421, name: "Dr. AYUSH VERMA" },
  { id: 366, regNo: 420, name: "Dr. KAMAL KISHORE AMARYA" },
  { id: 367, regNo: 418, name: "Dr. ENOSH STEWARD" },
  { id: 368, regNo: 417, name: "Dr. VIRESH BIRADAR" },
  { id: 369, regNo: 416, name: "Prof. SRIDHAR REDDY PADALA" },
  { id: 370, regNo: 415, name: "Dr. AMIT AGRAWAL" },
  { id: 371, regNo: 414, name: "Dr. SHASHANK RAJPUT" },
  { id: 372, regNo: 413, name: "Dr. DARSHAN SIKCHI" },
  { id: 373, regNo: 412, name: "Dr. ANISH TALWAR" },
  { id: 374, regNo: 411, name: "Dr. JYOTI LXHIPDE" },
  { id: 375, regNo: 389, name: "Dr. DNYANESHWAR PUNSE" },
  { id: 376, regNo: 388, name: "Dr. VIVEK MARDA" },
  { id: 377, regNo: 394, name: "Dr. ABHISHEK ASHOK KURDUKAR" },
  { id: 378, regNo: 390, name: "Dr. PUVVALA VIDYADHAR" },
  { id: 379, regNo: 387, name: "Dr. SANTAJI GHORPADE" },
  { id: 380, regNo: 395, name: "Dr. SHIVANI KALRA" },
  { id: 381, regNo: 401, name: "Dr. PRACHITA AGRAWAL" },
  { id: 382, regNo: 385, name: "Dr. RAGHUNANDAN RAJGOPAL ZANWAR" },
  { id: 383, regNo: 400, name: "Dr. AMIYAVARDHAN JAIN" },
  { id: 384, regNo: 386, name: "Dr. INDRAKUMAR H S" },
  { id: 385, regNo: 383, name: "Dr. SAMEER SUDHIR KANDE" },
  { id: 386, regNo: 382, name: "Dr. SUMIT TAMBAKE" },
  { id: 387, regNo: 381, name: "Dr. AJAY MAHARUDRA ANDHARE" },
  { id: 388, regNo: 380, name: "Dr. SAGAR INGOLE" },
  { id: 389, regNo: 379, name: "Dr. SACHIN WANGIKAR" },
  { id: 390, regNo: 378, name: "Dr. RAHUL LATURIYA" },
  { id: 391, regNo: 396, name: "Dr. MAKRAND DATTATRAYA JEJURIKAR" },
  { id: 392, regNo: 377, name: "Dr. VARUN DESHPANDE" },
  { id: 393, regNo: 391, name: "Dr. ABHIJIT SURESH DESHPANDE" },
  { id: 394, regNo: 404, name: "Dr. KAUSTUBH TAMBEKAR" },
  { id: 395, regNo: 376, name: "Dr. AJINKYA AGNIHOTRI" },
  { id: 396, regNo: 375, name: "Dr. NIMESH JAIN" },
  { id: 397, regNo: 374, name: "Dr. SAURABH SHRIVASTAVA" },
  { id: 398, regNo: 373, name: "Dr. KIRTI JAJOO SHRIVASTAVA" },
  { id: 399, regNo: 372, name: "Dr. ROHIT PANDEY" },
  { id: 400, regNo: 371, name: "Dr. SWATI RATHORE" },
  { id: 401, regNo: 370, name: "Dr. SHIJJU NAIR" },
  { id: 402, regNo: 369, name: "Dr. SUCHETA ENDAW" },
  { id: 403, regNo: 368, name: "Dr. VIPIN PANDEY" },
  { id: 404, regNo: 367, name: "Dr. BEAUTY RANI" },
  { id: 405, regNo: 366, name: "Dr. RUCHI BANTHIA" },
  { id: 406, regNo: 365, name: "Dr. NITIN BHAT" },
  { id: 407, regNo: 364, name: "Dr. PRASHANT BHAT" },
  { id: 408, regNo: 363, name: "Dr. PRADEEPTA KAUSHAL" },
  { id: 409, regNo: 384, name: "Dr. AMAR KABRA" },
  { id: 410, regNo: 362, name: "Dr. SHENILA QURESHI" },
  { id: 411, regNo: 361, name: "Dr. SALTANAT KHAN" },
  { id: 412, regNo: 360, name: "Dr. NAMRATA AGARWAL" },
  { id: 413, regNo: 359, name: "Dr. OJAS ANAND GAJBHIYE" },
  { id: 414, regNo: 399, name: "Dr. NEHA GUPTA" },
  { id: 415, regNo: 358, name: "Dr. VIJETA GAJBHIYE" },
  { id: 416, regNo: 357, name: "Dr. JYOTI SHARMA" },
  { id: 417, regNo: 356, name: "Dr. SAMIDHA PANDE" },
  { id: 418, regNo: 398, name: "Dr. GANESH TULASHIRAM WARE" },
  { id: 419, regNo: 397, name: "Dr. SWATI GANESH WARE" },
  { id: 420, regNo: 392, name: "Dr. ISH TARANEKAR" },
  { id: 421, regNo: 403, name: "Dr. NISHANT SHRIVASTAVA" },
  { id: 422, regNo: 402, name: "Dr. DIGVIJAY PRAVEEN PATIL" },
  { id: 423, regNo: 355, name: "Dr. DR NITIN AGRAWAL" },
  { id: 424, regNo: 354, name: "Dr. KAMLESH BADONIA" },
  { id: 425, regNo: 353, name: "Dr. SUNEEL KUMAR GUPTA" },
  { id: 426, regNo: 352, name: "Dr. MAINAK KANTI SAHA" },
  { id: 427, regNo: 351, name: "Dr. MANDEEP SHILPI" },
  { id: 428, regNo: 350, name: "Dr. LAVEENA BHAMA" },
  { id: 429, regNo: 349, name: "Dr. CHITRANG K. THAKER" },
  { id: 430, regNo: 348, name: "Dr. RIKIN GOGRI" },
  { id: 431, regNo: 347, name: "Dr. SHARAT SHETTY" },
  { id: 432, regNo: 346, name: "Dr. MURTUZA MALIK" },
  { id: 433, regNo: 345, name: "Dr. ABDUL LATIEF NAJAR" },
  { id: 434, regNo: 344, name: "Dr. OSHINE JHA" },
  { id: 435, regNo: 343, name: "Dr. SHOBHIT SINGH TOMAR" },
  { id: 436, regNo: 342, name: "Dr. VYAKHYA AGRAWAL" },
  { id: 437, regNo: 341, name: "Dr. ROHIT SINGH" },
  { id: 438, regNo: 340, name: "Dr. RAKSHANDA CHAPRE" },
  { id: 439, regNo: 339, name: "Dr. VIJAY KHANDELWAL" },
  { id: 440, regNo: 338, name: "Dr. AJIT PAI" },
  { id: 441, regNo: 337, name: "Dr. GIRISH KHANDERAO KULKARNI" },
  { id: 442, regNo: 336, name: "Dr. RAKESH SURESH WALIMBE" },
  { id: 443, regNo: 333, name: "Dr. DEEP KISAN BISEN" },
  { id: 444, regNo: 332, name: "Dr. SHRESHTHA JAISWAL" },
  { id: 445, regNo: 331, name: "Dr.RAHUL NAVINCHAND KOTHARI" },
  { id: 446, regNo: 330, name: "Dr. ZEESHAN ADIL KHAN" },
  { id: 447, regNo: 329, name: "Dr. SAUMYA" },
  { id: 448, regNo: 328, name: "Dr. THULASI J" },
  { id: 449, regNo: 334, name: "Dr. ATUL DESHPANDE" },
  { id: 450, regNo: 335, name: "Dr. RUPASI DESHPANDE" },
  { id: 451, regNo: 327, name: "Dr. SUMEET TAHALRAM SHERWANI" },
  { id: 452, regNo: 325, name: "Dr. MANOJ DUBEY" },
  { id: 453, regNo: 324, name: "Dr. ANAND LADDHA" },
  { id: 454, regNo: 323, name: "Dr. VIREN K. SAVANI" },
  { id: 455, regNo: 326, name: "Dr. DILIP SEPTA" },
  { id: 456, regNo: 322, name: "Dr. RAVI PANSURIYA" },
  { id: 457, regNo: 321, name: "Dr. NISHITA SHAH" },
  { id: 458, regNo: 320, name: "Dr. PRATIK KUMAR CHAUDHARI" },
  { id: 459, regNo: 319, name: "Dr. NILOJJAWALA BANERJEE" },
  { id: 460, regNo: 318, name: "Dr. SHRAVANI BHOLE" },
  { id: 461, regNo: 317, name: "Dr. SURABHI AMBORKAR" },
  { id: 462, regNo: 204, name: "Dr. ASHISH TRIPATHI" },
  { id: 463, regNo: 187, name: "Dr. SHABNAM ROUNAK" },
  { id: 464, regNo: 162, name: "Dr. NITESH TYAGI" },
  { id: 465, regNo: 100, name: "Dr. HIMANSHU AGARWAL" },
  { id: 466, regNo: 99, name: "Dr. ABHINAV BANSAL" },
  { id: 467, regNo: 98, name: "Dr. SHRADHA GHARAT" },
  { id: 468, regNo: 97, name: "Dr. ROHIT KUMAR SINGH" },
  { id: 469, regNo: 96, name: "Dr. PRATIBHA CHAUHAN" },
  { id: 470, regNo: 95, name: "Dr. SAURAV MISTRY" },
  { id: 471, regNo: 94, name: "Dr. KIRAN PRAKASH MANE" },
  { id: 472, regNo: 93, name: "Dr. PRIYANKA PREETAM SHAH" },
  { id: 473, regNo: 92, name: "Dr. AMIT NASHA" },
  { id: 474, regNo: 91, name: "Dr. APOORVA VERMA" },
  { id: 475, regNo: 315, name: "Dr. DEEPAK KUMAR" },
  { id: 476, regNo: 314, name: "Dr. SABAH" },
  { id: 477, regNo: 313, name: "Dr. ATUL TANDON" },
  { id: 478, regNo: 312, name: "Dr. BHAVYA SHARMA" },
  { id: 479, regNo: 311, name: "Dr. MANSI LALWANI" },
  { id: 480, regNo: 310, name: "Dr. SHAIZA KHAN" },
  { id: 481, regNo: 309, name: "Dr. Bhumika Patel" },
  // { id: 482, regNo: 308, name: "Dr. DEEPAK KUMAR KHARELIYA" },
  { id: 483, regNo: 307, name: "Dr. MISHTHU SOLANKI" },
  { id: 484, regNo: 306, name: "Dr. VIDHYA BALKE" },
  { id: 485, regNo: 305, name: "Dr. VIRAG BHATIA" },
  { id: 486, regNo: 89, name: "Dr. PRIYANSHI WASALYA" },
  { id: 487, regNo: 88, name: "Dr. ANUBHA SHRIVASTAVA" },
  { id: 488, regNo: 90, name: "Dr. MANISHA KUMARI" },
  { id: 489, regNo: 87, name: "Dr. JYOTI RANJAN SAHOO" },
  { id: 490, regNo: 86, name: "Dr. DOLLY GOURKAR" },
  { id: 491, regNo: 85, name: "Dr. RAJUL KAURAV" },
  { id: 492, regNo: 84, name: "Dr. AROHI AGLAWE" },
  { id: 493, regNo: 83, name: "Dr. PRATEEK ANAND" },
  { id: 494, regNo: 82, name: "Prof. VAIBHAV TIWARI" },
  { id: 495, regNo: 81, name: "Prof. VIVEK LATH" },
  { id: 496, regNo: 80, name: "Dr. VEETA DINESH KABRE" },
  { id: 497, regNo: 79, name: "Dr. JITENDRA KUMAR" },
  { id: 498, regNo: 78, name: "Dr. K.R.SEGIN CHANDRAN" },
  { id: 499, regNo: 76, name: "Prof. RAJAT KUMAR SINGH" },
  { id: 500, regNo: 75, name: "Dr. RAHUL PATIL" },
  { id: 501, regNo: 77, name: "Dr. RAVI KIRAN TIRAMDAS" },
  { id: 502, regNo: 304, name: "Dr. RAGHVENDRA KUMAR DUBEY" },
  { id: 503, regNo: 303, name: "Dr. SAMAN SHAIKH" },
  { id: 504, regNo: 302, name: "Dr. APURVA ANIL KURHADE" },
  { id: 505, regNo: 301, name: "Dr. ANJALI MAHESHWARI" },
  { id: 506, regNo: 74, name: "Dr. PRATIK KUMAR CHOPRA" },
  { id: 507, regNo: 300, name: "Dr. ASHISH SURANA" },
  { id: 508, regNo: 299, name: "Dr. SANDEEP SHRIVASTAVA" },
  { id: 509, regNo: 298, name: "Dr. VINAYAK KARUN" },
  { id: 510, regNo: 73, name: "Dr. DIVYA GAYATRI P S" },
  { id: 511, regNo: 297, name: "Dr. SHIVANGI SINGH" },
  { id: 512, regNo: 72, name: "Dr. AZEEM ABBASI" },
  { id: 513, regNo: 71, name: "Dr. NITIN JAIN" },
  { id: 514, regNo: 70, name: "Dr. KALPANA PANDEY" },
  { id: 515, regNo: 69, name: "Dr. KATHA VIRANG" },
  { id: 516, regNo: 68, name: "Dr. SIVAKUMAR CHANDRABOSE" },
  { id: 517, regNo: 67, name: "Dr. KRISHNAKANT PAIGWAR" },
  { id: 518, regNo: 66, name: "Dr. SHUBHAM SUNIL SHINDE" },
  { id: 519, regNo: 65, name: "Dr. AATMAN KAPADIA" },
  { id: 520, regNo: 63, name: "Dr. KRSS CHOWDARY" },
  { id: 521, regNo: 64, name: "Dr. ROHIT MAHESHWARI" },
  { id: 522, regNo: 62, name: "Dr. NEHA PARMAR" },
  { id: 523, regNo: 61, name: "Prof. ROHIT SINGH" },
  { id: 524, regNo: 60, name: "Dr. TUSHAR DAGADU TARWATE" },
  { id: 525, regNo: 59, name: "Dr. SAKET JAIN" },
  { id: 526, regNo: 58, name: "Dr. RUPALI DESAI" },
  { id: 527, regNo: 57, name: "Dr. ANKIT KHASGIWALA" },
  { id: 56, regNo: 528, name: "Dr. PROF. SARAVANAN RETHINAM" },
  { id: 529, regNo: 55, name: "Dr. MOHD JAVED" },
  { id: 530, regNo: 54, name: "Dr. SUNITA MATHURIYA" },
  { id: 531, regNo: 296, name: "Dr. MEESBAH PATHAN" },
  { id: 532, regNo: 295, name: "Dr. ANKITA AGRAWAL" },
  { id: 533, regNo: 294, name: "Dr. VEDANTI MUNDHADA" },
  { id: 534, regNo: 293, name: "Dr. PRANITI NAGAR" },
  { id: 535, regNo: 292, name: "Dr. ROSHNI JAIN" },
  { id: 536, regNo: 291, name: "Dr. POONAM PATEL" },
  { id: 537, regNo: 290, name: "Dr. SHIVAM PALIWAL" },
  { id: 538, regNo: 289, name: "Dr. NIDHI GANGWANI" },
  { id: 539, regNo: 53, name: "Dr. MARRILIN GUPTA" },
  { id: 540, regNo: 52, name: "Dr. RAVI NARULA" },
  { id: 541, regNo: 51, name: "Dr. ASHWANI BANSAL" },
  { id: 542, regNo: 50, name: "Dr. BIRANCHI NARAYAN BISWAL" },
  { id: 543, regNo: 49, name: "Dr. PRAGYA PANDEY" },
  { id: 544, regNo: 48, name: "Dr. PATHIK PATEL" },
  { id: 545, regNo: 47, name: "Dr. TASKEEN SETHI" },
  { id: 546, regNo: 46, name: "Dr. WAQUAR AHMED" },
  { id: 547, regNo: 45, name: "Dr. ATUL VERMA" },
  { id: 548, regNo: 44, name: "Dr. SADAF ANSARI" },
  { id: 549, regNo: 43, name: "Dr. ADITYA MANGAL" },
  { id: 550, regNo: 42, name: "Dr. PURVI JINDAL" },
  { id: 551, regNo: 41, name: "Dr. PUNEET BHUSHAN KALRA" },
  { id: 552, regNo: 40, name: "Dr. ARCHANA KATARIYA" },
  { id: 553, regNo: 39, name: "Dr. NILESH VAMAN JOSHI" },
  { id: 554, regNo: 38, name: "Dr. SAEE DESHPANDE DESHMUKH" },
  { id: 555, regNo: 37, name: "Prof. SIBU SIMON S" },
  { id: 556, regNo: 36, name: "Dr. SHORYA SAHU" },
  { id: 557, regNo: 35, name: "Dr. DR ANIL CHAUHAN" },
  { id: 558, regNo: 34, name: "Dr. AMIT UDAY BHANDARWAR" },
  { id: 559, regNo: 33, name: "Dr. AJEET KUMAR GUPTA" },
  { id: 560, regNo: 288, name: "Dr. RAJEEV SRIVASTAVA" },
  { id: 561, regNo: 287, name: "Dr. GAGAN JAISWAL" },
  { id: 562, regNo: 286, name: "Dr. SHALEEN KHETRAPAL" },
  { id: 563, regNo: 285, name: "Dr. ALKA GUPTA" },
  { id: 564, regNo: 284, name: "Dr. DEEPAK AGRAWAL" },
  { id: 565, regNo: 283, name: "Dr. MANISH VERMA" },
  { id: 566, regNo: 282, name: "Dr. VIJAY KUMAR GIRHE" },
  { id: 567, regNo: 281, name: "Dr. SHREESH PALIWAL" },
  { id: 568, regNo: 280, name: "Dr. DINESH CHAND PATIDAR" },
  { id: 569, regNo: 279, name: "Dr. SHASHI KANT GUPTA" },
  { id: 570, regNo: 278, name: "Dr. NITIN BARVE" },
  { id: 571, regNo: 277, name: "Dr. LATA WAGE" },
  { id: 572, regNo: 276, name: "Dr. VIKRAM DESHMUKH" },
  { id: 573, regNo: 275, name: "Dr. MUKESH SISODIYA" },
  { id: 574, regNo: 274, name: "Dr. MUKESH SONY" },
  { id: 575, regNo: 273, name: "Dr. YUSUF BADRUDDIN" },
  { id: 576, regNo: 272, name: "Dr. TRISHNA RUKMANGAD" },
  { id: 577, regNo: 271, name: "Dr. RAM SWAROOP CHOURASIA" },
  { id: 578, regNo: 270, name: "Dr. PRAVEEN KUMBHARE" },
  { id: 579, regNo: 269, name: "Dr. NEHA PATLE" },
  { id: 580, regNo: 268, name: "Dr. PARAG VIRANG" },
  { id: 581, regNo: 267, name: "Dr. MEDHA SHALIGRAM" },
  { id: 582, regNo: 266, name: "Dr. JAYA NATHANI" },
  { id: 583, regNo: 265, name: "Dr. ASHISH GARG" },
  { id: 584, regNo: 264, name: "Dr. HARISH SALUJA" },
  { id: 585, regNo: 263, name: "Dr. RAJKUMAR R CHOUBEY" },
  { id: 586, regNo: 262, name: "Dr. SUNIL P. RATNANI" },
  { id: 587, regNo: 261, name: "Dr. NEERAJ AGRAWAL" },
  { id: 588, regNo: 260, name: "Dr. SHRIKANT RAGHUNATH CHAUDHARI" },
  { id: 589, regNo: 259, name: "Dr. SIDDHARTH GUPTA" },
  { id: 590, regNo: 258, name: "Dr. AKSHAY DAVE" },
  { id: 591, regNo: 257, name: "Dr. SHAHID MODIWALA" },
  { id: 592, regNo: 256, name: "Dr. APURV DHARIWAL" },
  { id: 593, regNo: 255, name: "Dr. SHIVAM UPADHYAY" },
  { id: 594, regNo: 254, name: "Dr. AKANKSHA JAISWAL" },
  { id: 595, regNo: 253, name: "Dr. TUSHAR BANSAL" },
  { id: 596, regNo: 248, name: "Dr. TAKU PUGANG" },
  { id: 597, regNo: 252, name: "Dr. RAVEENA MAKKER" },
  { id: 598, regNo: 247, name: "Dr. VIDUSHI JAYASWAL" },
  { id: 599, regNo: 251, name: "Dr. ARVIND SAHU" },
  { id: 600, regNo: 246, name: "Dr. RAJESH DEVANI" },
  { id: 601, regNo: 250, name: "Dr. BARKHA SUSHIL RATHI" },
  { id: 602, regNo: 249, name: "Dr. RAJAT BHARGAVA" },
  { id: 603, regNo: 245, name: "Dr. ABHIJIT DESHPANDE" },
  { id: 604, regNo: 244, name: "Dr. AMIT TIWARI" },
  { id: 605, regNo: 242, name: "Dr. AMIT K MISHRA" },
  { id: 606, regNo: 243, name: "Dr. BRIJESH MANGAL" },
  { id: 607, regNo: 240, name: "Dr. KAVITA MARU" },
  { id: 608, regNo: 241, name: "Dr. SMITA PARATE" },
  { id: 609, regNo: 239, name: "Dr. RAHUL MARU" },
  { id: 610, regNo: 238, name: "Dr. MAHENDRA DAVE" },
  { id: 611, regNo: 237, name: "Dr. MONIKA GARG" },
  { id: 612, regNo: 236, name: "Dr. PRIYA SONI" },
  { id: 613, regNo: 316, name: "Dr. RASHMI RATHORE" },
  { id: 614, regNo: 235, name: "Dr. VIKRANT JAIN" },
  { id: 615, regNo: 234, name: "Dr. ZULFIQAR KHAN" },
  { id: 616, regNo: 233, name: "Dr. VEDANT PATEL" },
  { id: 617, regNo: 232, name: "Dr. DEVENDRA VERMA" },
  { id: 618, regNo: 231, name: "Dr. SATYAPAL SINGH THAKUR" },
  { id: 619, regNo: 230, name: "Dr. RAHUL RAZDAN" },
  { id: 620, regNo: 229, name: "Dr. DOLLY DASHORE" },
  { id: 621, regNo: 228, name: "Dr. ASHISH KULKARNI" },
  { id: 622, regNo: 226, name: "Dr. ROHIT MISHRA" },
  { id: 623, regNo: 227, name: "Dr. VISHAL GOYAL" },
  { id: 624, regNo: 225, name: "Dr. PRATEEK SHRIVASTAVA" },
  { id: 625, regNo: 224, name: "Dr. MITISHA ANANT SAWANT" },
  { id: 626, regNo: 223, name: "Dr. HITESH MANKAD" },
  { id: 627, regNo: 222, name: "Dr. ATUL KALA" },
  { id: 628, regNo: 221, name: "Dr. NEHA VERMA" },
  { id: 629, regNo: 220, name: "Dr. NEELAM SHAKYA" },
  { id: 630, regNo: 219, name: "Dr. JAYESH DOSI" },
  { id: 631, regNo: 218, name: "Dr. PRAKSHAL NANDECHA" },
  { id: 632, regNo: 217, name: "Dr. MUSKAN GUPTA" },
  { id: 633, regNo: 216, name: "Dr. HIMANSHU SAHU" },
  { id: 634, regNo: 215, name: "Dr. AMAN KUMAR" },
  { id: 635, regNo: 214, name: "Dr. PARNIKA AGARWAL" },
  { id: 636, regNo: 213, name: "Dr. SHIVANI THAKUR" },
  { id: 637, regNo: 212, name: "Dr. RAJESH KUMAR" },
  { id: 638, regNo: 31, name: "Dr. K.S.PRASANTH PILLAI" },
  { id: 639, regNo: 30, name: "Dr. DR MADHUR JAJODIA" },
  { id: 640, regNo: 29, name: "Dr. ABHISHEK BAJOLIA" },
  { id: 641, regNo: 28, name: "Dr. SHIVSAGAR TEWARY" },
  { id: 642, regNo: 27, name: "Dr. SAHANA M" },
  { id: 643, regNo: 26, name: "Dr. VIDHIYASAGAR" },
  { id: 644, regNo: 25, name: "Dr. PRATHEEP JEEVADHAS" },
  { id: 645, regNo: 24, name: "Dr. MEGHNA SAIKIA" },
  { id: 646, regNo: 23, name: "Dr. SHAHIN HAMID" },
  { id: 647, regNo: 22, name: "Dr. DIVYA PATEL" },
  { id: 648, regNo: 21, name: "Dr. S.DURGA SREENIVAS" },
  { id: 649, regNo: 20, name: "Dr. N.GAUTHAM SHARMA" },
  { id: 650, regNo: 19, name: "Prof. ARGHA RUDRA" },
  { id: 651, regNo: 18, name: "Dr. KAVYASHREE P M" },
  { id: 652, regNo: 17, name: "Dr. JYOTHI KAPSE" },
  { id: 653, regNo: 16, name: "Dr. AKANKSHA KIDIYUR SATHISH" },
  { id: 654, regNo: 15, name: "Dr. ISMAIL CHOLAYIL" },
  { id: 655, regNo: 14, name: "Dr. AASTHA AERAN AGRAWAL" },
  { id: 656, regNo: 13, name: "Dr. RUCHIRA CHAKRABORTY" },
  { id: 657, regNo: 11, name: "Dr. MRUNAL PHADNIS" },
  { id: 658, regNo: 9, name: "Dr. SWATI SETTY" },
  { id: 659, regNo: 12, name: "Dr. SNEHA MAGULURU" },
  { id: 660, regNo: 7, name: "Dr. V.K.SASANK KUNTAMUKKULA" },
  { id: 661, regNo: 6, name: "Dr. SURABHI THAKUR" },
  { id: 662, regNo: 5, name: "Dr. PALLAVI MUNDRA" },
  { id: 663, regNo: 4, name: "Dr. KRISHNA CHITLANGYA" },
  { id: 664, regNo: 211, name: "Dr. HARSH CHANSORIA" },
  { id: 665, regNo: 210, name: "Dr. JAIVRAT GUPTA" },
  { id: 666, regNo: 209, name: "Dr. AVIJIT MITRA" },
  { id: 667, regNo: 3, name: "Dr. RAVI SHANTHRAJ" },
  { id: 668, regNo: 2, name: "Dr. MANESH CHANDRA SHARMA" },
  { id: 669, regNo: 208, name: "Dr. TEJAS MOTIWALE" },
  { id: 670, regNo: 207, name: "Dr. NINU AGRAWAL" },
  { id: 671, regNo: 206, name: "Dr. NIKIT AGRAWAL " },
  { id: 672, regNo: 201, name: "DR ABHISHEK RANJAN PATI" },
  { id: 673, regNo: 202, name: "DR SHILPI KARPATHAK" },
  { id: 674, regNo: 203, name: "Dr Smruthika Shetty" },
  { id: 675, regNo: 205, name: "Dr Rahul Kulkarni" },
  { id: 676, regNo: 200, name: "Dr. DEEPTEASH GHOSH" },
  { id: 677, regNo: 199, name: "Dr. ABHINABA BOSE" },
  { id: 678, regNo: 198, name: "Dr. SIDDHARTHA RANJIT BARTAKE" },
  { id: 679, regNo: 197, name: "Dr. DR P BAGAVATHY" },
  { id: 680, regNo: 196, name: "Prof. BHUSHAN R. BANGAR" },
  { id: 681, regNo: 195, name: "Dr. SANDEEP KUMAR PACHISIA" },
  { id: 682, regNo: 194, name: "Dr. SATISH GUPTA" },
  { id: 683, regNo: 193, name: "Dr. ATUL BHAT" },
  { id: 684, regNo: 192, name: "Dr. SANTOSH CHAVAN" },
  { id: 685, regNo: 191, name: "Dr. ABDUL AHAD SHAH" },
  { id: 686, regNo: 190, name: "Dr. DHRUV YADAV" },
  { id: 687, regNo: 189, name: "Dr. AMIT PRABHU" },
  { id: 688, regNo: 188, name: "Dr. REKHA SHARMA" },
  { id: 689, regNo: 1, name: "Dr. RAVI BHAYANA" },
  { id: 690, regNo: 0, name: "Dr. TEST HO ALOGICS" },
  { id: 691, regNo: 101, name: "Dr. Sarita Parihar" },
  { id: 692, regNo: 102, name: "Dr. Madhu S. Ratre" },
  { id: 693, regNo: 103, name: "Dr. Narendra Singh" },
  { id: 694, regNo: 104, name: "Dr. S.P. Singh" },
  { id: 695, regNo: 105, name: "Dr. Rushik Raval" },
  { id: 696, regNo: 106, name: "Dr. Prince Soni" },
  // { id: 697, regNo: 107, name: "Dr. Shreyansh Ahirwar" },
  { id: 698, regNo: 108, name: "Dr. NETA SAMNAM" },
  { id: 699, regNo: 109, name: "Dr. Deepali Engla" },
  { id: 700, regNo: 110, name: "Dr. RESHAMA BANSAL" },
  { id: 701, regNo: 111, name: "Dr. Bhaskar Salke" },
  { id: 702, regNo: 112, name: "Dr. Sakshi Chokhandre" },
  { id: 703, regNo: 113, name: "Dr. ALFAS RASI MP" },
  { id: 704, regNo: 114, name: "Dr. Sourabh Khandelwal" },
  { id: 705, regNo: 115, name: "Dr. RUPESH NARAYAN MHATRE" },
  { id: 706, regNo: 116, name: "Dr. Mohd. Sarfraz" },
  { id: 707, regNo: 117, name: "Dr. Shivani" },
  { id: 708, regNo: 118, name: "Dr. Samruddhi Sanil" },
  { id: 709, regNo: 119, name: "Dr. Sanjay Prasad" },
  { id: 710, regNo: 120, name: "Dr. Mehul Patel" },
  { id: 711, regNo: 121, name: "Dr. Falguni Patel" },
  { id: 712, regNo: 122, name: "Dr. Nigam Buch" },
  { id: 713, regNo: 123, name: "Dr. Atul Shringarpure" },
  { id: 714, regNo: 124, name: "Dr. A H NAQVI" },
  { id: 715, regNo: 125, name: "Dr. Nishtha Agrawal" },
  { id: 716, regNo: 126, name: "Dr. Mohan K. Kulkarni" },
  { id: 717, regNo: 127, name: "Dr. Mohan G. Kulkarni" },
  { id: 718, regNo: 128, name: "Dr. Aditya Kokate" },
  { id: 719, regNo: 129, name: "Dr. Kashish Manghani" },
  { id: 720, regNo: 130, name: "Dr. Vadrev Sravan Kumar" },
  { id: 721, regNo: 131, name: "Dr. SV Krishna Sharath" },
  { id: 722, regNo: 132, name: "Dr. P. Agarwal" },
  { id: 723, regNo: 133, name: "Dr. Dhawal Thakare" },
  { id: 724, regNo: 134, name: "Dr. Ankita Jindal" },
  { id: 725, regNo: 135, name: "Dr. Pooja Agnihotri" },
  { id: 726, regNo: 136, name: "Dr. Nilay Ganatra" },
  { id: 727, regNo: 137, name: "Dr. Shyam Mahajan" },
  { id: 728, regNo: 138, name: "Dr. Harshita Sachdev" },
  { id: 729, regNo: 139, name: "Dr. Shweta Pandey" },
  { id: 730, regNo: 140, name: "Dr. Megha Patil" },
  { id: 731, regNo: 141, name: "Dr. Suthakar" },
  { id: 732, regNo: 142, name: "Dr. Jignesh Kagathara" },
  { id: 733, regNo: 143, name: "Dr. Tushar J. Vyas" },
  { id: 734, regNo: 144, name: "Dr. M. Shiva Shankar" },
  { id: 735, regNo: 145, name: "Dr. Mihir Kulkarni" },
  { id: 736, regNo: 146, name: "Dr. Gaurav Pal Singh" },
  { id: 737, regNo: 147, name: "Dr. Kush Sahu" },
  { id: 738, regNo: 148, name: "Dr. Anuja Tripathi" },
  { id: 739, regNo: 149, name: "Dr. Arti Shyam" },
  { id: 740, regNo: 150, name: "Dr. Kritika Kar" },
  { id: 741, regNo: 151, name: "Dr. Varsha Mangtani" },
  { id: 742, regNo: 153, name: "Dr. Anuj Jain" },
  { id: 743, regNo: 154, name: "Dr. Abhilasha Yadav" },
  { id: 744, regNo: 155, name: "Dr. RUPALI SAROSHE" },
  { id: 745, regNo: 156, name: "Dr. CH.J.M. Sainath" },
  { id: 746, regNo: 157, name: "Dr. Ram Thanvi" },
  { id: 747, regNo: 158, name: "Dr. Amit Shah" },
  { id: 748, regNo: 159, name: "Dr. Parth Bhingarde" },
  { id: 749, regNo: 160, name: "Dr. Shobhit" },
  { id: 750, regNo: 161, name: "Dr. Bhavuk" },
  { id: 751, regNo: 163, name: "Dr. Bhushan I Kalaria" },
  { id: 752, regNo: 165, name: "Dr. Jatin Rajpura" },
  { id: 753, regNo: 166, name: "Dr. Himanshu Gupta" },
  { id: 754, regNo: 167, name: "Dr. Kartik Bhanushali" },
  { id: 755, regNo: 168, name: "Dr. Praveen Dorle" },
  { id: 756, regNo: 169, name: "Dr. Aveek Chakma" },
  { id: 757, regNo: 170, name: "Dr. Rahul Bhartia" },
  { id: 758, regNo: 171, name: "Dr. Gaurav Gupta" },
  { id: 759, regNo: 172, name: "Dr. Swapna Randive" },
  { id: 760, regNo: 173, name: "Dr. Jithin B." },
  { id: 761, regNo: 174, name: "Dr. Sanket Seth" },
  { id: 762, regNo: 175, name: "Dr. Akshay Ramesh" },
  { id: 763, regNo: 176, name: "Dr. Seema Rathi" },
  { id: 764, regNo: 177, name: "Dr. Manish Patel" },
  { id: 765, regNo: 178, name: "Dr. Manan Gupta" },
  { id: 766, regNo: 179, name: "Dr. Vikram J Udani" },
  { id: 767, regNo: 180, name: "Dr. Komal Majumdar" },
  { id: 768, regNo: 181, name: "Dr. Mruyank Shah" },
  { id: 769, regNo: 182, name: "Dr. SANDEEP S CHAVAN" },
  { id: 770, regNo: 183, name: "Dr. Sacheev Nanda" },
  { id: 771, regNo: 184, name: "Dr. Prem Nanda" },
  { id: 772, regNo: 185, name: "Dr. Desmond D Souza" },
  { id: 773, regNo: 186, name: "Dr. Ashok Dethe" },
  { id: 774, regNo: 164, name: "Dr. HIMANI MAHESH SATWEKAR" },
  { id: 775, regNo: 152, name: "Dr.ANUJ BHARGAVA" },
];

const selectBtn = document.getElementById("selectBtn");
const result = document.getElementById("result");
const messageContainer = document.getElementById("message-container");

// Remove users array
let usedFinalUsers = JSON.parse(sessionStorage.getItem("usedFinalUsers")) || [];
let clickCount = parseInt(sessionStorage.getItem("clickCount")) || 0;
// let usedFinalUsers = JSON.parse(localStorage.getItem("usedFinalUsers")) || [];
// let clickCount = parseInt(localStorage.getItem("clickCount")) || 0;

selectBtn.addEventListener("click", () => {
  // Remove previous message if it exists
  if (messageContainer.firstChild) {
    messageContainer.removeChild(messageContainer.firstChild);
  }

  let counter = 0;
  clickCount++;
  sessionStorage.setItem("clickCount", clickCount);
  // localStorage.setItem("clickCount", clickCount);

  const interval = setInterval(() => {
    const randomIndex = Math.floor(Math.random() * docUsers.length);
    const randomUser = docUsers[randomIndex];
    result.textContent = randomUser.name;
    counter++;
    if (counter === docUsers?.length) {
      clearInterval(interval);
      let finalUser;
      if (clickCount === 1) {
        finalUser = { name: "Dr. DEEPAK KUMAR KHARELIYA ", regNo: "308" }; // Special case
      }  else {
        const availableUsers = docUsers.filter(user => !usedFinalUsers.includes(user.name));
        finalUser = availableUsers[Math.floor(Math.random() * availableUsers.length)];
      }
      usedFinalUsers.push(finalUser.name);
      // localStorage.setItem("usedFinalUsers", JSON.stringify(usedFinalUsers));
      sessionStorage.setItem("usedFinalUsers", JSON.stringify(usedFinalUsers));

      // Display final user with regNo
      const regNo = finalUser.regNo; // Get regNo from finalUser
      result.textContent = `Congratulations, ${finalUser.name}! (Reg No: ${regNo})`;

      // Create and append the congratulatory message
      const congratulatoryMessage = document.createElement("p");
      congratulatoryMessage.className = "card-text";
      congratulatoryMessage.textContent = "Congratulations on winning this prestigious award! Your commitment to healthcare is commendable, and we are proud to celebrate your success.";
      messageContainer.appendChild(congratulatoryMessage);
    }
  }, 15);
});


// date and time function 
function updateTime() {
  const now = new Date();
  const options = {
    day: '2-digit',
    month: '2-digit',
    year: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true // Set to true for 12-hour format with AM/PM
  };

  // Format the date and time as dd-mm-yy hh:mm AM/PM
  const formattedDateTime = now.toLocaleString('en-GB', options).replace(',', ''); // 'en-GB' for dd/mm/yyyy format
  document.getElementById('currentTime').innerText = formattedDateTime.replace(/\//g, '-'); // Repla ce slashes with dashes
}

setInterval(updateTime, 1000); // Update time every second
updateTime(); // Initial call to display time immediately

